# Generated by Django 6.0.3 on 2026-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_local', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField()),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('dia_semana', models.IntegerField()),
                ('fim_de_semana', models.BooleanField(default=False)),
                ('feriado', models.BooleanField(default=False)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('consumo_kwh', models.FloatField()),
                ('anomalia', models.BooleanField(default=False)),
                ('tipo_anomalia', models.CharField(default='normal', max_length=50)),
                ('potencia_kw_ac_ref', models.FloatField()),
                ('consumo_base_estimado', models.FloatField(blank=True, null=True)),
                ('intensidade_operacional_local', models.FloatField(blank=True, null=True)),
                ('sensibilidade_temperatura_local', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
